spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url:        # Vault가 주입
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host:     # Vault가 주입
      port:
      password:

jwt:
  secret:       # Vault가 주입
  expiration-in-ms: 86400000

server:
  port: 8080

oci:
  vault:
    secret-ids: "ocid1.vaultsecret...prod용..."  # TODO: 실제 OCID로 교체
  storage:
    namespace: ax1dvc8vmenm
    region: ap-chuncheon-1
    bucket: snuclear-asset

course-sync:
  auto:
    fixedDelayMillis: 10800000
  sugang:
    excelUrl: "https://sugang.snu.ac.kr/sugang/cc/cc100InterfaceExcel.action"
    refererUrl: "https://sugang.snu.ac.kr/sugang/cc/cc100InterfaceSrch.action"
    pageSize: 9999
    language: "ko"
    connectTimeoutMillis: 5000
    readTimeoutMillis: 30000
  defaultTarget:
    year: 2026
    semester: SPRING

